### ISSUE TITLE
Why combining x25519 with P503 and x448 with P751

### ISSUE THREAD

**Issue by kriskwiatkowski** [franziskuskiefer/pq-tls-draft#14]
I'm wondering what is the reason for combining x25519 with P503 and x448 with P751?
x25519 gives me 32-byte shared secret, but P503 gives only 16-byte shared secret. Similarly x448 gives 56-byte shared secret and P751 gives 24-byte shared secret. Why not to use X25519 only for both cases?

**Comment by dconnolly** [comment]
P751 gives about 192bits¹ of quantum-resistant level security (and possibly more²), so larger than classical X25519 at 128bit. X448 provides about 224bit classical security so it would at least cover what P751 is supposed to provide in quantum-resistant security, if that fails/is broken. 

At least that's how I interpreted it, @franziskuskiefer. 

1: https://sike.org/files/SIDH-spec.pdf, page 38 table 5.1
2: https://eprint.iacr.org/2019/103.pdf, "Quantum cryptanalysis in the RAM model: Claw-finding attacks on SIKE"

**Comment by kriskwiatkowski** [comment]
I know what draft says. It was me who has put it there. 
Now I'm wondering if it is actually correct

**Comment by kriskwiatkowski** [comment]
Ok, it comes from here (just putting reference before I forget again):
https://tools.ietf.org/html/rfc7748

For x25519:
```
4.1.  Curve25519
   For the ~128-bit security level, the prime 2^255 - 19 is recommended
   for performance on a wide range of architectures. 
```

For x448
```
4.2.  Curve448
   For the ~224-bit security level, the prime 2^448 - 2^224 - 1 is
   recommended for performance on a wide range of architectures. 
```

**Comment by kriskwiatkowski** [comment]
btw: this table will probably be changed soon

**Comment by franziskuskiefer** [comment]
> btw: this table will probably be changed soon

What changes have you planned?

**Comment by kriskwiatkowski** [comment]
I think there may be an update for SIKE in PQC Round 2 which would change this table a bit (following 2019/103). I'm waiting for details actually.
